version: 2

python:
  version: 3
  install:
    - method: pip
      path: "git+https://github.com/MaineKuehn/usim.git#egg=usim"
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/conf.py
