version: 2

python:
  version: 3
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: docs/conf.py
